apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: auth-rbac-so
spec:
  scaleTargetRef:
    name: auth-rbac
  minReplicaCount: 1
  maxReplicaCount: 4
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "80"
