apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: energy-management-so
spec:
  scaleTargetRef:
    name: energy-management
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "75"
