apiVersion: v1
kind: Service
metadata:
  name: energy-management
  labels:
    app.kubernetes.io/name: energy-management
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: energy-management
  ports:
    - name: http
      port: 80
      targetPort: http
