apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: ml-predictor
    newName: us-central1-docker.pkg.dev/borel-sigma-prod/borel-sigma-containers/ml-predictor
    newTag: dev
