apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app.kubernetes.io/name: payments
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/name: payments
  ports:
    - name: http
      port: 80
      targetPort: http
