apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-world
  labels:
    app.kubernetes.io/name: hello-world
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
