apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces-app.yaml
  - hello-world-dev.yaml
  - energy-management-dev.yaml
  - vendor-ecosystem-dev.yaml
  - iot-ingestion-dev.yaml
  - auth-rbac-dev.yaml
  - sealed-secrets-app.yaml
